// Brazos County Foreclosure Notices — September 2026
// Auto-generated from extract.py — do not edit by hand.
// To update: run `python scripts/extract.py <new_pdf> data/notices.json`
// then copy the array contents here.

const DATA = [
  {
    id: 1,
    address: "2214 Johnny Lyon Ct",
    city: "Bryan",
    state: "TX",
    zip: "77807",
    debtor: "Monica Garcia & Charles Augusta Langston Jr.",
    lender: "Village Capital & Investment LLC",
    servicer: "Village Capital & Investment LLC",
    amount: 292503,
    deedDate: "February 13, 2024",
    instrument: "1521721",
    type: "Substitute trustee",
    subdivision: "Edgewater Subdivision Phase 5, Lot 148, Block 14",
    notes: "Single family residential. Filed by Brock & Scott, Irving TX.",
    highlight: false
  },
  {
    id: 2,
    address: "2009 Chief St",
    city: "Bryan",
    state: "TX",
    zip: "77807",
    debtor: "William Caldwell & Latoya Caldwell",
    lender: "PennyMac Loan Services LLC",
    servicer: "PennyMac Loan Services LLC",
    amount: 271326,
    deedDate: "March 30, 2023",
    instrument: "1498615",
    type: "Substitute trustee",
    subdivision: "Pleasant Hill Section 2 Phase 2, Lot 18, Block 5",
    notes: "Filed case 26-02382. Filed by Tromberg Miller Morris & Partners PLLC, Plano TX.",
    highlight: false
  },
  {
    id: 3,
    address: "1708 Beaver Pond Ct",
    city: "Bryan",
    state: "TX",
    zip: "77807",
    debtor: "Rupert Horka & Pamela Horka",
    lender: "PHH Asset Services LLC / Onity Mortgage Corp",
    servicer: "Onity Mortgage Corporation (f/k/a PHH Mortgage)",
    amount: 130500,
    deedDate: "April 13, 2018",
    instrument: "Book 14615, Page 109 / Doc 1326751",
    type: "Substitute trustee",
    subdivision: "Shirewood Addition Phase V, Lot 25, Block 1",
    notes: "Case 25-000439-671-2. Filed by Mackie Wolf Zientz & Mann PC, Dallas TX.",
    highlight: false
  },
  {
    id: 4,
    address: "303 Capps Drive",
    city: "College Station",
    state: "TX",
    zip: "77845",
    debtor: "Agustin Alejandro Ramirez & Alicia Raquel Mota",
    lender: "Academy Mortgage Corp (via MERS) / Freedom Mortgage Corp",
    servicer: "Freedom Mortgage Corporation",
    amount: 137464,
    deedDate: "Unknown",
    instrument: "T.S. #2026-22349-TX",
    type: "Substitute trustee",
    subdivision: "Timbercreek at Steep Hollow Phase II, Lot 8, Block 2",
    notes: "Filed by Nestor Solutions LLC for Freedom Mortgage. Contact: (855) 690-5900. Sale info: xome.com or (800) 758-8052.",
    highlight: false
  },
  {
    id: 5,
    address: "Manufactured home — Brazos County",
    city: "Bryan",
    state: "TX",
    zip: "",
    debtor: "Joe Pleasant a/k/a Joe Anthony Pleasant & Cynthia Pleasant a/k/a Cynthia Denease Pleasant",
    lender: "21st Mortgage Corporation",
    servicer: "21st Mortgage Corporation",
    amount: 135000,
    deedDate: "November 7, 2019",
    instrument: "1377805",
    type: "Trustee",
    subdivision: "2020 Champion Manufactured Home, Serial No. 110-000-M-A004033A",
    notes: "Manufactured/mobile home. Trustee: K. Clifford Littlefield. Filed by Upton Mickits & Heymann LLP, Corpus Christi. Tel: (361) 884-0612.",
    highlight: false
  },
  {
    id: 6,
    address: "Warren tract — Brazos County",
    city: "Bryan",
    state: "TX",
    zip: "",
    debtor: "Warren Brayton Davis III a/k/a Warren Brayton Davis",
    lender: "US Bank National Association (Trustee)",
    servicer: "Auction.com LLC / Tejas Corporate Services LLC",
    amount: 325000,
    deedDate: "Unknown",
    instrument: "Unknown",
    type: "Substitute trustee",
    subdivision: "Land parcel — full legal description in deed of trust",
    notes: "Trustee: Auction.com LLC OR Tejas Corporate Services LLC, c/o Robertson Anschutz Schneid Crane & Partners PLLC, Alpharetta GA 30004. PH: (470) 321-7112.",
    highlight: false
  },
  {
    id: 7,
    address: "510 Ash St",
    city: "Bryan",
    state: "TX",
    zip: "77803",
    debtor: "Craig Morgan",
    lender: "Brazos Valley Schools Credit Union",
    servicer: "Brazos Valley Schools Credit Union",
    amount: 470000,
    deedDate: "Unknown",
    instrument: "Unknown",
    type: "Trustee",
    subdivision: "Bryan — legal description in deed of trust",
    notes: "Local lender: Brazos Valley Schools Credit Union. Highest value Bryan property in this batch. Trustee: H. Brad Parker P.C., 700 Louisiana St Suite 3950, Houston TX 77002. PH: (713) 892-5588.",
    highlight: false
  },
  {
    id: 8,
    address: "4117 Muncaster",
    city: "College Station",
    state: "TX",
    zip: "77845",
    debtor: "Alice Christopherr Moya",
    lender: "M109 Investments LLC",
    servicer: "M109 Investments LLC",
    amount: 230000,
    deedDate: "September 26, 2019",
    instrument: "Volume 15600, Page 296",
    type: "Trustee",
    subdivision: "Castlegate II Subdivision Section 101, Lot 9, Block 15",
    notes: "Private lender — not a bank. Trustee: J. Fred Bayliss. Private lenders often prefer negotiated exits over courthouse steps.",
    highlight: false
  },
  {
    id: 9,
    address: "603 Lincoln Ave",
    city: "College Station",
    state: "TX",
    zip: "77840",
    debtor: "James Watson, Trustee of The Cornelius Searcy Living Trust & James Watson Individually",
    lender: "Vicki R. Searcy Manuel (judgment creditor)",
    servicer: "Brazos County Sheriff",
    amount: 63349,
    deedDate: "October 16, 2025 (judgment date)",
    instrument: "17-002320-CV-361",
    type: "Sheriff",
    subdivision: "Lauterstein, Lot 1 & 50 ft of 4 — BCAD Property ID 31259",
    notes: "SHERIFF'S SALE — not a mortgage foreclosure. Judgment lien of $63,349.32 from district court case 17-002320-CV-361. Sale by Wayne Dicky, Sheriff. Judgment liens sell at deep discounts. College Station location near A&M.",
    highlight: true
  }
];
